on:
  workflow_call:
    inputs:
      test-value:
        description: A test
        type: string
    outputs:
      output-value:
        description: an output
        value: ${{ jobs.testing.outputs.output-value }}
      secret-value:
        description: a secret
        value: ${{ jobs.testing.outputs.secret-value }}

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Doing testing
    steps:
      - uses: actions/checkout@v4
      - name: An Test
        id: testing
        run: |
          ls -alh
          echo "output-value=this is some output" >> "${GITHUB_OUTPUT}"
          echo "secret-value=${secret}" >> "${GITHUB_OUTPUT}"
        env:
          secret: ${{ secrets.TEST_SECRET }}
